### PR TITLE
Build complete and integrated with Travis

### PR DESCRIPTION
**Pull request by ColinEberhardt**
relates to #101

This completes the build process changes, now everything runs under grunt, with the following build pipeline:

+ JSLint
+ JS Unit Test (Chrome) - this is skipped in Travis
+ Transpile
+ Java & C Test
+ JS Package
+ Java Package

I've removed the makefile, also rather than fetching Java dependencies via wget I've just committed them , feels like a much simpler solution to me!

The one remaining thing I haven't tackled is making this work under Windows, should be relatively straightforward, but I've not got access to a Windows machine right now. @prenaux - do you have time to give this a try?

The build now packages both JavaScript and Java, I've not idea what to do with the C code - any takers?!

Before merging I'd like to see this tested by a few different people as it is a significant change.

### CODE REVIEW

**Comment by prenaux** [comment]
Sure, I can look at it tonight or tomorrow. Let me look at the C code as-well, I actually use that ;)

**Comment by ColinEberhardt** [comment]
Thanks, that would be great.

**Comment by prenaux** [comment]
I took a quick look, overall there shouldn't be any big issue. Main changes to make:
- env path separator for java ":" (POSIX) -> ";" (Windows)
- gcc -> cl
- probably would be best to quote all paths on the command line so that it works if someone uses a directory with space character somewhere.

I can make those changes, but maybe it'd be better if this was merged first as I'm not sure how to contribute to a PR directly. (I've checkout the PR locally following this: https://gist.github.com/piscisaureus/3342247)

Once this is merged I can make the updates for Windows and submit a new PR for that.

**Comment by ColinEberhardt** [comment]
Thanks @prenaux - I'd be happy to see the Windows changes integrated after this is merged.

**Comment by prenaux** [comment]
No problem.

**Comment by vjeux** [comment]
:+1:

**Comment by ColinEberhardt** [comment]
@prenaux - this change is merged now, if you need any help with the Windows changes, give me a shout

**Comment by prenaux** [comment]
@ColinEberhardt: great I'll do that asap, I'll let you know if there's any issue.

**Comment by prenaux** [comment]
Done, see PR #109.

**Pull request merged**
