### PR TITLE
Syntax highlight C code in README

### PR DESCRIPTION
**Pull request by vjeux**

### CODE REVIEW

**Comment by emilsjolander** [comment]
lgtm

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
I will not rubber stamp and land your change for you @vjeux!  I can import it for you and you can get your change reviewed by someone though :)

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3914024).

**Pull request closed without merging**
