### PR TITLE
Force measure flag

### PR DESCRIPTION
**Pull request by marco-cova**
We can force the measure function of a node, if set, to be called.
The resulting sizes will be used for the layout traversal.

### CODE REVIEW

**Comment by emilsjolander** [comment]
Changes look good. For sake of documentation please write a paragraph (in this pull request) about why we want this and when it would be useful to set this flag.

**Comment by marco-cova** [comment]
We can force the measure function of a node to be called if we need to perform operations based on the sizes of the node. 
e.g. We might want to add/operate on the children of the current node if it's wide enough. https://github.com/facebook/css-layout/pull/187 will properly support changing the number of children of a node while measuring it.

**Comment by emilsjolander** [comment]
Sounds good.

**Comment by marco-cova** [comment]
We decided not to change css-layout but to work around this on higher level.

**Pull request closed without merging**
