### PR TITLE
Add pom.xml

### PR DESCRIPTION
**Pull request by sherdeadlock**
Would css-layout deploy to maven central? 
Maven is convenient to manage dependencies.

### CODE REVIEW

**Comment by vjeux** [comment]
@lucasr can you review this? I have never published anything to maven, but seems like a good idea.

**Comment by ColinEberhardt** [comment]
Nice idea, how about adding the steps required to deploy a versioning release to Maven within the release documentation here:

https://github.com/facebook/css-layout/tree/master/dist

**Comment by sherdeadlock** [comment]
I am trying to publish it to my maven group, and I will contribute the process if I succeeded.

### refs
* http://central.sonatype.org/pages/ossrh-guide.html
* http://central.sonatype.org/pages/apache-maven.html
* https://github.com/spotify/docker-maven-plugin/blob/master/pom.xml

**Comment by emilsjolander** [comment]
This is an old pull request and there have been and are coming a lot of changes. I'm closing this.

**Pull request closed without merging**
