### PR TITLE
Ensure RTL nodes layout correctly on multiple passes

### PR DESCRIPTION
**Pull request by gethinw**
As-per #190, when laying out a node with direction: 'rtl', if the same node is laid out multiple times its layout will become incorrect.

This PR fixes the underlying issue in the JavaScript and C implementations, by ensuring that appropriate dimensions are fully reset at the beginning of a new layout pass. It appears from a quick glance that the issue shouldn't exist in the C# and Java versions (a full reset is already performed), but I've been struggling to get the tests running against those. Any help with this would be much appreciated!

### CODE REVIEW

**Comment by pragmatrix** [comment]
To make the C# tests pass, you could add a forwarding function:

```c#
    static void layoutNode(CSSNode node, float parentMaxWidth, float parentMaxHeight, CSSDirection? parentDirection)
    {
        LayoutEngine.layoutNode(new CSSLayoutContext(), node, parentMaxWidth, parentMaxHeight, parentDirection);
    }
```
before `/** START_GENERATED **/` in `LayoutEngineTest.cs`. Fixing the Java tests should be similar.

**Comment by emilsjolander** [comment]
Looks good! Could you please rebase?

**Comment by gethinw** [comment]
Sure - rebase done.

**Comment by emilsjolander** [comment]
@gethinw Could you please sign out CLA before we merge this? code.facebook.com/cla Thank you!

**Comment by emilsjolander** [comment]
This pull request was accidentally closed when the layout of the repo changed. If you could open a pull request based on the latest master that would be awesome.

**Pull request closed without merging**
