### PR TITLE
Fix an error initializing `needsCrossTrailingPos`

### PR DESCRIPTION
**Pull request by joce**
Signed-off-by: joce <joce@unity3d.com>

### CODE REVIEW

**Comment by emilsjolander** [comment]
Thanks @joce, I can't believe we missed this. Could you please sign the CLA and I would be happy to merge this.

**Comment by joce** [comment]
The corporate CLS is currently in our legal department's hands. Should not be too long before we get the OK.

**Comment by emilsjolander** [comment]
There have been a bunch of renamed going on and given that this change is so small i'm going to go ahead and do it myself to spare you the trouble of rebasing the diff. Thanks for bringing this to our attention!

**Comment by joce** [comment]
Thanks man.

Sorry for not getting this done myself. Unity legal still hasn't cleared
the CLA. :-(

**Comment by emilsjolander** [comment]
No worries! I understand this isn't on you 👍 Looking forward to future PRs

**Pull request closed without merging**
