### PR TITLE
Java: Expose extra functionality on CSSNode

### PR DESCRIPTION
**Pull request by rigdern**
This change is needed to support inline views on React Native for Android (facebook/react-native#8619).

### CODE REVIEW

**Comment by rigdern** [comment]
The README mentions that you can run the tests with `buck test //:CSSLayout`. Does this run the Java tests as well?

**Comment by emilsjolander** [comment]
@rigdern I'll update the readme with java testing as well. `buck test //:CSSLayout_java` will run the java tests

**Comment by emilsjolander** [comment]
Could you please rebase again? I'm back from vacation now and would be happy to merge this

**Comment by emilsjolander** [comment]
@rigdern Did you get a change to rebase this?

**Comment by rigdern** [comment]
@emilsjolander Sorry for the delay. We're having some discussion in facebook/react-native#8619 about the right solution in that PR. Depending on that outcome of that discussion, this PR might not be needed. If it's alright with you, I'd like to have this PR sit here until we come to a conclusion on facebook/react-native#8619.

If you prefer, I can close this PR and reopen it later if it's needed.

**Comment by emilsjolander** [comment]
No, keep it open :) just wanted a status update. Thanks!

**Comment by emilsjolander** [comment]
@rigdern Any update on this? I checked the linked PR but not much has happened in a while

**Comment by emilsjolander** [comment]
I'm closing this. Feel free to open another pull request later if you want 👍

**Pull request closed without merging**
