### PR TITLE
Added package.json

### PR DESCRIPTION
**Pull request by ColinEberhardt**
Thanks for the awesome library - I'm already using it in one of my projects. In order to manage this as a proper dependency (rather than cut and paste the code into my repo - yuck!), I need a `package.json` file. It would be great if you could add this.

### CODE REVIEW

**Comment by vjeux** [comment]
Nice! Can you fix the CI build and i'll merge it in :)

**Comment by ColinEberhardt** [comment]
Sure, just off to bed, will take a look at the build tomorrow 😀

**Comment by vjeux** [comment]
Awesome :)

**Comment by ColinEberhardt** [comment]
@vjeux - thanks to #26 it's working now. See #31 for the updated PR. Thank you :-)

**Pull request closed without merging**
