### PR TITLE
If the measure function is defined: only return from execution of lay…

### PR DESCRIPTION
**Pull request by lukasreichart**
…outNode, when the node has no children.

I'am currently working on a new implementation of the TextView element in react-native.
My implementation uses the node->measure function to calculate the height of the element, but a TextView may also have subviews. If thats the case it's necessary to execute the rest of the layoutNode function and not stopping it after line 318.
This change does not affect the behaviour of the other module ( RCText ), that uses the measure function, because this element will always have a children_count of zero.

### CODE REVIEW

**Comment by vjeux** [comment]
Thanks, that makes sense! I can't wait to see your TextView code. I've always wanted to be able to put arbitrary elements there but couldn't find time to implement it!

**Comment by paramaggarwal** [comment]
@lukasreichart Just like you use this for a `<TextView>`, I use it for `<Image>`. With `measure` I'm able to define an aspect ratio for the image and then have it take the entire width of the device - taking the necessary height as required. Super useful!

Not sure how to add support to also do this other way round - calculate height given a width.

**Comment by lukasreichart** [comment]
@paramaggarwal sounds great and I'd love to try it.  :+1: Have you published a npm module or created a PR for react-native?

**Comment by paramaggarwal** [comment]
@lukasreichart Unfortunately your change here hasn't ended up in RN yet... Open PR: https://github.com/facebook/react-native/pull/1776

I have a generic implementation for all RCTView subclasses here: https://github.com/facebook/react-native/pull/1538 - simply pass an `aspectRatio` prop to your views. So you could make _any_ view behave like a rigid boxed rectangle and all the children would layout normally.

The PR is blocked at the moment as `measure` can only calculate a height given a width and not vice-versa. Any thoughts on how to make `measure` more generic to be able to measure both ways?

**Pull request merged**
