### PR TITLE
Add inline definition for Microsoft Visual Studio

### PR DESCRIPTION
**Pull request by anql**
The inline keyword is available only in C++. The __inline and __forceinline keywords are available in both C and C++. For compatibility with previous versions, _inline is a synonym for __inline.

https://msdn.microsoft.com/en-us/library/z8y1yy88(v=vs.120).aspx

### CODE REVIEW

**Comment by emilsjolander** [comment]
Thanks! although __inline is vendor specific (msvc) so can we only define it for msvc?

**Comment by anql** [comment]
Only define it for msvc to fix issues like this
http://stackoverflow.com/questions/24736304/unable-to-use-inline-in-declaration-get-error-c2054

**Comment by emilsjolander** [comment]
Exactly, could you update the PR?

**Comment by emilsjolander** [comment]
@anql Why did you close this PR?

**Comment by anql** [comment]
:(   sorry, It’s my mistake. 
Google search "how to update pull request github",
http://stackoverflow.com/questions/9790448/how-to-update-a-pull-request
reopen and click "Update branch".
:)

**Comment by emilsjolander** [comment]
@anql with the update you are still using `__inline` on non msvc compilers. Could you instead check for the _MSC_VER macro? All compilers with support for c99 will support the standard `inline` keyword.

**Comment by anql** [comment]
default

**Comment by emilsjolander** [comment]
ah sorry! Totally missed that in the diff view 👍 I'll import and merge this. Thanks!

**Pull request closed without merging**
