### PR TITLE
Check layout instead of style before setting height and width to whatever is set in layout

### PR DESCRIPTION
**Pull request by emilsjolander**
`isDimDefined` checks is node.style[axis] is defined while in these places we do not care about `node.style[axis]` but `node.layout[axis]`. This caused parent height not to be correctly propagated to children.

### CODE REVIEW

**Comment by vjeux** [comment]
Can you add a test case?

**Comment by emilsjolander** [comment]
@vjeux will do

**Comment by lucasr** [comment]
@emilsjolander Does this fix alone that bug with a specific height being passed to the measure function?

**Comment by emilsjolander** [comment]
@lucasr no. that is more a limitation than a bug

**Comment by emilsjolander** [comment]
@vjeux rebased to include test case. Also changed implementation to avoid some duplicate logic.

**Comment by emilsjolander** [comment]
nvm this broke a lot of things in the transpiling. Fixing.

**Comment by lucasr** [comment]
Nice, thanks!

**Pull request merged**
