### PR TITLE
Supress warning about incorrect license SPDX type

### PR DESCRIPTION
**Pull request by ptomasroos**
Added correct SPDX license type in order to get rid of the warning NPM was throwing each invocation

### CODE REVIEW

**Comment by ptomasroos** [comment]
Sorry will rebase this since I've started working on a csharp LayoutEngine in master in order to support Windows Phone.

**Comment by pragmatrix** [comment]
@ptomasroos Just a note here, I am already maintaining an "unofficial" csharp port with all tests passing, including a nuget package at https://github.com/pragmatrix/css-layout . You are welcome to use it.

**Comment by ptomasroos** [comment]
Are you considering sending it back to the main repo?

**Comment by pragmatrix** [comment]
@vjeux would your team consider taking in a pull request for a C# port if it complies to the contribution requirements?

**Comment by ptomasroos** [comment]
I think its a start for making a Windows Phone entrance to the react-native platform. Makes sense.

**Comment by vjeux** [comment]
@pragmatrix absolutely! Would be awesome :)

**Comment by spicyj** [comment]
@pragmatrix Can you not use the C version directly?

**Comment by spicyj** [comment]
Also, this should be BSD-3-Clause.

**Comment by ptomasroos** [comment]
I think using a c lib on a windows phone is not applicable. 

I guess the same reason applies to android / Java?

**Comment by ptomasroos** [comment]
Quick google indead shows that Windows Phone can reuse c / c++ libraries.
Then I think it makes a lot of sense to wrap the C library in order to make the maintainability better for the 4th platform.

Reference: https://msdn.microsoft.com/en-us/library/windows/apps/jj681687%28v=vs.105%29.aspx <https://msdn.microsoft.com/en-us/library/windows/apps/jj681687(v=vs.105).aspx>

**Pull request closed without merging**
