### PR TITLE
[Issue facebook/css-layout#127]: content re-layout of stretched items

### LINKED ISSUE #127: View not stretching vertically in column layout
### @corbt said in https://github.com/facebook/react-native/issues/2724#issuecomment-140902710

I think I may have found a couple of inconsistencies that are related to my problem. I've created what I believe are equivalent layouts in React Native and HTML/CSS that appear to demonstrate different flexbox behavior. Am I just crazy or is this a bug?

#### HTML
JSFiddle [here](https://jsfiddle.net/awtLxLpm/)

#### React Native
```jsx
<View style={{flexDirection: 'row', alignItems: 'stretch', width: 150}}>
  <View style={{backgroundColor: 'red'}}>
    <View style={{backgroundColor: 'green'}}>
      <Text style={{backgroundColor: 'purple', alignSelf: 'center'}}>
        Column 1
      </Text>
    </View>
  </View>
  <Text style={{backgroundColor: '#B2DBFF', height: 150}}>Column 2</Text>
</View>
```

Output on my Android device:
device

#### Differences
In React Native the intermediary green `div` doesn't expand to fill the column vertically, and the "Column 1" text is not centered vertically either. On my machine (OS X/Chrome 45) the HTML version does.

### PR DESCRIPTION
**Pull request by alebo**
Trying to fix #127.

### CODE REVIEW

**Comment by woehrl01** [comment]
@alebo: Great! this also seems to solve #83 

[But I had to pass](https://github.com/facebook/css-layout/pull/145/files#diff-a69100b1f123b9ecff85330a582e3faaR932): `node.MaxWidth` instead of just `maxWidth`

**Comment by woehrl01** [comment]
@alebo: there is still an issue with this one. If you have `MarginTop` set. The result looks like that the value gets doubled somehow.

**Comment by alebo** [comment]
@woehrl01 Thanks for your comments. I can investigate it further.

**Comment by woehrl01** [comment]
@alebo @vjeux  I just looked at the tests, and in my opintion those are false negatives. If you add those children, the layout should be `HasNewLayout`, what do you think?

@alebo according your update, sorry to bother you but if you have a lot of nested streching layouts, sometimes the position gets fully set to 0 (they are left aligned), and so they are off. So I think this is still not totally correct :(

I think that reseting the `mainAxis`is enough:

```
child.layout[pos[mainAxis]] = 0;
```

at least in my scenarios the output is now as expected.

**Comment by alebo** [comment]
@woehrl01 if an item has MarginTop and MarginLeft resetting both axes might be required. Also, those failed tests seem to be related to cases when item's sizes are determined by text measuring. I'm going to continue looking into this.

**Comment by alebo** [comment]
This also fixes #100

**Comment by woehrl01** [comment]
@alebo looks really good to me. Awesome job! :+1:

**Comment by woehrl01** [comment]
@vjeux @lucasr any news on this one?

**Comment by corbt** [comment]
What still needs to be done to get this merged? It has tests and (to my unfamiliar-with-css-layout eye) doesn't appear too complex.

**Comment by janmonschke** [comment]
@alebo looks good to me!

Would be great to get this merged :)

**Comment by alebo** [comment]
I'm ready to rebase this and resolve conflicts as soon as there's any feedback from the project maintainers.

**Comment by corbt** [comment]
pinging @vjeux again, more people are running into this issue over at RN.

**Comment by vjeux** [comment]
I'm sorry but won't be looking into it in a while. @lucasr do you have time to review this?

**Comment by lucasr** [comment]
I think I need a little more context on the changes before reviewing (see questions).

**Comment by lucasr** [comment]
And thanks for the contribution! ;-)

**Comment by senpng** [comment]
image
image

This ''blue line" is not center;

when I set the parent view's height and the blue line is center

image
image

I think it is bug at here. because the blue line's parent view's height is determine.

**Comment by andresn** [comment]
@alebo @lucasr @vjeux any chance we can get some eyes on this again? I reduced the problem to a very simple example and there's a basic gap in meeting spec in RN:

Screenshot (including iPhone simulator): http://screencast.com/t/H3Da1mQhmLX3
Fiddle: http://jsfiddle.net/drdrace/w95u54z6/1/

**Comment by jsendros** [comment]
@andresn @alebo in #171 I built on top of the changes made here to fix another issue. None of the tests added/changed here break due to my changes in #171, so I expect this will fix your issue as well. :)

**Comment by alebo** [comment]
@lucasr, is there a requirement that a pull request must contain a single commit? Could @jsendros and myself create a collaborative PR with his changes and mine represented by separate commits (so that everyone can get their deserved praise and respect :)?

**Comment by lucasr** [comment]
@alebo Could you please just push the exact diff from #171 here so that I can merge? @jsendros doesn't really mind having you as the author of this change.

**Comment by alebo** [comment]
I've cherry-picked @jsendros's updates on top of my rebased commit. @lucasr, @jsendros, please confirm again, that you'd really like me to squash the two commits into one.

**Comment by jsendros** [comment]
Squash away!

**Pull request merged**
